services:
  - type: web
    name: dsa-study-hub-backend
    env: node
    buildCommand: "cd server && npm install"
    startCommand: "cd server && npm start"
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
